<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyVersion>2.0.1</AssemblyVersion>
    <FileVersion>2.0.1</FileVersion>
    <Version>2.0.1</Version>
    <PackageId>SqlCodeEditor</PackageId>
    <Authors>victor-wiki</Authors>
    <Description>SQL syntax highlighting.</Description>
    <PackageProjectUrl>https://github.com/victor-wiki/SqlCodeEditor</PackageProjectUrl>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
    <Title>SqlCodeEditor</Title>
    <PackageReadmeFile>SqlCodeEditor.md</PackageReadmeFile>
    <PackageReleaseNotes>Change config file from assembly resource to content file.</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Utils\**" />
    <EmbeddedResource Remove="Utils\**" />
    <None Remove="Utils\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Document\HighlightingStrategy\SyntaxModes\ResourceSyntaxModeProviderEx.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Gui\TextEditorControlBase.resx" />
  </ItemGroup>

  <ItemGroup>
    <None Remove=".gitignore" />    
    <None Remove="Resources\Function.png" />
    <None Remove="Resources\Function_Trigger.png" />
    <None Remove="Resources\Keyword.png" />
    <None Remove="Resources\Schema.png" />
    <None Remove="Resources\Table.png" />
    <None Remove="Resources\TableColumn.png" />
    <None Remove="Resources\TextEditorControl.bmp" />
    <None Remove="Resources\View.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Config\SyntaxHighlighting\Mode.xsd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <Content Include="Config\SyntaxHighlighting\MySql.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <Content Include="Config\SyntaxHighlighting\PlSql.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <Content Include="Config\SyntaxHighlighting\PostgreSql.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <Content Include="Config\SyntaxHighlighting\SqliteSql.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <Content Include="Config\SyntaxHighlighting\SyntaxModes.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <Content Include="Config\SyntaxHighlighting\TSql.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>

  <ItemGroup>	
    <EmbeddedResource Include="Resources\Function.png" />
    <EmbeddedResource Include="Resources\Function_Trigger.png" />
    <EmbeddedResource Include="Resources\Keyword.png" />
    <EmbeddedResource Include="Resources\Schema.png" />
    <EmbeddedResource Include="Resources\Table.png" />
    <EmbeddedResource Include="Resources\TableColumn.png" />
    <EmbeddedResource Include="Resources\TextEditorControl.bmp" />
    <EmbeddedResource Include="Resources\View.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\license.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\SqlCodeEditor.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>  

</Project>
